name: PR-BUILD-IMAGE

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'README.md'

env:
  IMAGE_NAME: ghcr.io/bnb-chain/greenfield-storage-provider
  IMAGE_SOURCE: https://github.com/bnb-chain/greenfield-storage-provider

jobs:
  # Push image to GitHub Packages.
  build-image:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: bufbuild/buf-setup-action@v1.14.0
        with:
          version: 1.14.0
          buf_user: "${{ secrets.BUF_REGISTRY_USER }}"
          buf_api_token: "${{ secrets.BUF_REGISTRY_SECRET }}"
      
      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - run: |
          make install-tools
          make buf-gen

      - name: Build image
        run: |
          docker build . \
          --build-arg "GH_TOKEN=${{ secrets.GH_SECRET }}" \
          --label "org.opencontainers.image.source=${IMAGE_SOURCE}" \
          --label "org.opencontainers.image.revision=${{ github.event.pull_request.head.sha }}" \
          --label "org.opencontainers.image.ref.name=${{ github.event.pull_request.number }}" \
          --label "org.opencontainers.image.licenses=LGPL-3.0,GPL-3.0" \
          -f ./Dockerfile -t "${IMAGE_NAME}:${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}"
          docker images

      - name: Log into registry
        run: echo "${{ secrets.GH_SECRET }}" | docker login ghcr.io -u constwz --password-stdin

      - name: Push image
        run: |
          docker push "${IMAGE_NAME}:${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}"
          